sudo: required
language: java

services:
  - docker

jdk:
  - oraclejdk8
script:
  - gradle clean build


deploy:
  provider: script
  before_script: cd build-scripts
  script: bash publish.sh
  on:
    branch: develop