spring:
  datasource:
    url: jdbc:postgresql://${db.host}/${db.name}
    username: ${db.user}
    password: ${db.pass}
  jooq:
    sql-dialect: POSTGRES
server:
  port: 8080
  context-path: /api
logging.level.org.springframework.web: DEBUG